eg_view_class:
    resource: "@EGViewClassBundle/Resources/config/routing.yml"
    prefix:   /

eg_core:
    resource: "@EGCoreBundle/Resources/config/routing.yml"
    prefix:   /

eg_class:
    resource: "@EGClassBundle/Resources/config/routing.yml"
    prefix:   /class

