eg_follow_up:
    resource: "@EGFollowUpBundle/Resources/config/routing.yml"
    prefix:   /follow-up

eg_game:
    resource: "@EGGameBundle/Resources/config/routing.yml"
    prefix:   /games

eg_view_class:
    resource: "@EGViewClassBundle/Resources/config/routing.yml"
    prefix:   /class

eg_core:
    resource: "@EGCoreBundle/Resources/config/routing.yml"
    prefix:   /

eg_class:
    resource: "@EGClassBundle/Resources/config/routing.yml"
    prefix:   /admin/class

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

eg_user:
    resource: "@EGUserBundle/Resources/config/routing.yml"
    prefix:   /