eg_follow_up:
    resource: "@EGFollowUpBundle/Resources/config/routing.yml"
    prefix:   /follow-up

eg_game:
    resource: "@EGGameBundle/Resources/config/routing.yml"
    prefix:   /games

eg_view_class:
    resource: "@EGViewClassBundle/Resources/config/routing.yml"
    prefix:   /class

eg_core:
    resource: "@EGCoreBundle/Resources/config/routing.yml"
    prefix:   /

eg_class:
    resource: "@EGClassBundle/Resources/config/routing.yml"
    prefix:   /admin/class

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

eg_user:
    resource: "@EGUserBundle/Resources/config/routing.yml"
    prefix:   /