eg_user_homepage:
    path:     /admin
    defaults: { _controller: EGUserBundle:User:index }

eg_user_add:
    path: /admin/add
    defaults:
        _controller: EGUserBundle:User:add

eg_user_edit:
    path:    /admin/edit/{id}
    defaults:
        _controller: EGUserBundle:User:edit

eg_user_delete:
    path:    /admin/delete/{id}
    defaults:
        _controller: EGUserBundle:User:delete

eg_user_profile:
    path: /profile/{id}
    defaults:
        _controller: EGUserBundle:User:profile