eg_user_homepage:
    path:     /
    defaults: { _controller: EGUserBundle:User:index }

eg_user_add:
    path: /add
    defaults:
        _controller: EGUserBundle:User:add

eg_user_edit:
    path:    /edit/{id}
    defaults:
        _controller: EGUserBundle:User:edit

eg_user_delete:
    path:    /delete/{id}
    defaults:
        _controller: EGUserBundle:User:delete