eg_class_homepage:
    path:     /
    defaults: { _controller: EGClassBundle:Class:index }

eg_class_view:
    path:     /view/{id}
    defaults:
        _controller: EGClassBundle:Class:view
    requirements:
        id: \d+

eg_class_add:
    path:    /add
    defaults:
        _controller: EGClassBundle:Class:add

eg_class_edit:
    path:     /edit/{id}
    defaults:
        _controller: EGClassBundle:Class:edit
    requirements:
        id: \d+

eg_class_delete:
    path:     /delete/{id}
    defaults:
        _controller: EGClassBundle:Class:delete
    requirements:
        id: \d+

eg_class_delete_all:
    path:     /delete-all/{id}
    defaults:
        _controller: EGClassBundle:Class:deleteAll
    requirements:
        id: \d+

eg_pupil_add:
    path:    /pupil/add/{id}
    defaults:
        _controller: EGClassBundle:Pupil:add
    requirements:
            id: \d+
eg_pupil_delete:
    path:    /pupil/delete/{id}
    defaults:
        _controller: EGClassBundle:Pupil:delete
    requirements:
            id: \d+