eg_game_homepage:
    path:     /
    defaults: { _controller: EGGameBundle:Games:index }

eg_game_play:
    path: /play/{id}
    defaults:
        _controller: EGGameBundle:Games:play
    requirements:
        id: \d+