eg_admin_game:
    path: /admin
    defaults:
        _controller: EGGameBundle:Games:admin

eg_admin_add_game:
    path: /admin/add
    defaults:
        _controller: EGGameBundle:Games:add

eg_admin_edit_game:
    path: /admin/edit/{id}
    defaults:
        _controller: EGGameBundle:Games:edit
    requirements:
        id: \d+

eg_game_homepage:
    path:     /{id}
    defaults: { _controller: EGGameBundle:Games:index }
    requirements:
        id: \d+

eg_game_play:
    path: /play/{pupil}/{id}
    defaults:
        _controller: EGGameBundle:Games:play
    requirements:
        id: \d+

